// frontend/src/pages/GeneralSettings/Settings/Interface/index.vue
<template>
  <div class="w-screen h-screen overflow-hidden bg-theme-bg-container flex">
    <Sidebar />
    <div
      :style="{ height: isMobile ? '100%' : 'calc(100% - 32px)' }"
      class="relative md:ml-[2px] md:mr-[16px] md:my-[16px] md:rounded-[16px] bg-theme-bg-secondary w-full h-full overflow-y-scroll p-4 md:p-0"
    >
      <div class="flex flex-col w-full px-1 md:pl-6 md:pr-[86px] md:py-6 py-16">
        <div class="w-full flex flex-col gap-y-1 pb-6 border-white light:border-theme-sidebar-border border-b-2 border-opacity-10">
          <div class="items-center">
            <p class="text-lg leading-6 font-bold text-white">
              {{ t('customization.interface.title') }}
            </p>
          </div>
          <p class="text-xs leading-[18px] font-base text-white text-opacity-60">
            {{ t('customization.interface.description') }}
          </p>
        </div>
        <ThemePreference />
        <LanguagePreference />
        <MessageDirection />
      </div>
    </div>
  </div>
</template>

<script setup>
import Sidebar from '@/components/SettingsSidebar/index.vue'
import { isMobile } from 'react-device-detect'
import { useI18n } from 'vue-i18n'
import LanguagePreference from '../components/LanguagePreference/index.vue'
import ThemePreference from '../components/ThemePreference/index.vue'
import { MessageDirection } from '../components/MessageDirection/index.vue'

const { t } = useI18n()
</script>

// frontend/src/pages/GeneralSettings/Settings/Interface/index.jsx
import Sidebar from "@/components/SettingsSidebar";
import { isMobile } from "react-device-detect";
import { useTranslation } from "react-i18next";
import LanguagePreference from "../components/LanguagePreference";
import { MessageDirection } from "../components/MessageDirection";

export default function InterfaceSettings() {
  const { t } = useTranslation();

  return (
    <div className="w-screen h-screen overflow-hidden bg-theme-bg-container flex">
      <Sidebar />
      <div
        style={{ height: isMobile ? "100%" : "calc(100% - 32px)" }}
        className="relative md:ml-[2px] md:mr-[16px] md:my-[16px] md:rounded-[16px] bg-theme-bg-secondary w-full h-full overflow-y-scroll p-4 md:p-0"
      >
        <div className="flex flex-col w-full px-1 md:pl-6 md:pr-[86px] md:py-6 py-16">
          <div className="w-full flex flex-col gap-y-1 pb-6 border-white light:border-theme-sidebar-border border-b-2 border-opacity-10">
            <div className="items-center">
              <p className="text-lg leading-6 font-bold text-white">
                {t("customization.interface.title")}
              </p>
            </div>
            <p className="text-xs leading-[18px] font-base text-white text-opacity-60">
              {t("customization.interface.description")}
            </p>
          </div>
          <LanguagePreference />
          <MessageDirection />
        </div>
      </div>
    </div>
  );
}
