// frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/PromptReply/index.jsx
import { memo, useRef, useEffect } from "react";
import { Warning } from "@phosphor-icons/react";
import UserIcon from "../../../../UserIcon";
import renderMarkdown from "@/utils/chat/markdown";
import Citations from "../Citation";
import {
  THOUGHT_REGEX_CLOSE,
  THOUGHT_REGEX_COMPLETE,
  THOUGHT_REGEX_OPEN,
  ThoughtChainComponent,
} from "../ThoughtContainer";

const PromptReply = ({
  uuid,
  reply,
  pending,
  error,
  workspace,
  sources = [],
}) => {
  const assistantBackgroundColor = "bg-theme-bg-chat";

  if (!reply && sources.length === 0 && !pending && !error) return null;

  if (pending) {
    return (
      <div
        className={`flex justify-center items-end w-full ${assistantBackgroundColor}`}
      >
        <div className="py-6 px-4 w-full flex gap-x-5 md:max-w-[80%] flex-col">
          <div className="flex gap-x-5">
            <WorkspaceProfileImage workspace={workspace} />
            <div className="mt-3 ml-5 dot-falling light:invert"></div>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div
        className={`flex justify-center items-end w-full ${assistantBackgroundColor}`}
      >
        <div className="py-6 px-4 w-full flex gap-x-5 md:max-w-[80%] flex-col">
          <div className="flex gap-x-5">
            <WorkspaceProfileImage workspace={workspace} />
            <span
              className={`inline-block p-2 rounded-lg bg-red-50 text-red-500`}
            >
              <Warning className="h-4 w-4 mb-1 inline-block" /> Could not
              respond to message.
              <span className="text-xs">Reason: {error || "unknown"}</span>
            </span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      key={uuid}
      className={`flex justify-center items-end w-full ${assistantBackgroundColor}`}
    >
      <div className="py-8 px-4 w-full flex gap-x-5 md:max-w-[80%] flex-col">
        <div className="flex gap-x-5">
          <WorkspaceProfileImage workspace={workspace} />
          <RenderAssistantChatContent
            key={`${uuid}-prompt-reply-content`}
            message={reply}
            messageId={uuid}
          />
        </div>
        <Citations sources={sources} />
      </div>
    </div>
  );
};

export function WorkspaceProfileImage({ workspace }) {
  if (!!workspace.pfpUrl) {
    return (
      <div className="relative w-[35px] h-[35px] rounded-full flex-shrink-0 overflow-hidden">
        <img
          src={workspace.pfpUrl}
          alt="Workspace profile picture"
          className="absolute top-0 left-0 w-full h-full object-cover rounded-full bg-white"
        />
      </div>
    );
  }

  return <UserIcon user={{ uid: workspace.slug }} role="assistant" />;
}

function RenderAssistantChatContent({ message, messageId }) {
  const contentRef = useRef("");
  const thoughtChainRef = useRef(null);

  useEffect(() => {
    const thinking =
      message.match(THOUGHT_REGEX_OPEN) && !message.match(THOUGHT_REGEX_CLOSE);

    if (thinking && thoughtChainRef.current) {
      thoughtChainRef.current.updateContent(message);
      return;
    }

    const completeThoughtChain = message.match(THOUGHT_REGEX_COMPLETE)?.[0];
    const msgToRender = message.replace(THOUGHT_REGEX_COMPLETE, "");

    if (completeThoughtChain && thoughtChainRef.current) {
      thoughtChainRef.current.updateContent(completeThoughtChain);
    }

    contentRef.current = msgToRender;
  }, [message]);

  const thinking =
    message.match(THOUGHT_REGEX_OPEN) && !message.match(THOUGHT_REGEX_CLOSE);
  if (thinking)
    return (
      <ThoughtChainComponent
        ref={thoughtChainRef}
        content=""
        messageId={messageId}
      />
    );

  return (
    <div className="flex flex-col gap-y-1">
      {message.match(THOUGHT_REGEX_COMPLETE) && (
        <ThoughtChainComponent
          ref={thoughtChainRef}
          content=""
          messageId={messageId}
        />
      )}
      <span
        className="break-words"
        dangerouslySetInnerHTML={{ __html: renderMarkdown(contentRef.current) }}
      />
    </div>
  );
}

export default memo(PromptReply);

// frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/PromptReply/index.vue
<script setup>
import { ref, watch, defineComponent, h } from 'vue'
import { Warning } from '@phosphor-icons/vue'
import UserIcon from '@/components/UserIcon/index.vue'
import renderMarkdown from '@/utils/chat/markdown'
import Citations from '../Citation/index.vue'
import ThoughtContainer, {
  THOUGHT_REGEX_CLOSE,
  THOUGHT_REGEX_COMPLETE,
  THOUGHT_REGEX_OPEN,
} from '../ThoughtContainer/index.vue'

const props = defineProps({
  uuid: String,
  reply: String,
  pending: Boolean,
  error: String,
  workspace: Object,
  sources: {
    type: Array,
    default: () => []
  },
  closed: {
    type: Boolean,
    default: true
  }
})

const assistantBackgroundColor = 'bg-theme-bg-chat'

// WorkspaceProfileImage component
export const WorkspaceProfileImage = defineComponent({
  props: {
    workspace: Object
  },
  setup(props) {
    if (!!props.workspace?.pfpUrl) {
      return () => h('div', { class: 'relative w-[35px] h-[35px] rounded-full flex-shrink-0 overflow-hidden' }, [
        h('img', {
          src: props.workspace.pfpUrl,
          alt: 'Workspace profile picture',
          class: 'absolute top-0 left-0 w-full h-full object-cover rounded-full bg-white'
        })
      ])
    }

    return () => h(UserIcon, { user: { uid: props.workspace?.slug }, role: 'assistant' })
  }
})

// RenderAssistantChatContent component
const RenderAssistantChatContent = defineComponent({
  props: {
    message: String
  },
  setup(props) {
    const contentRef = ref('')
    const thoughtChainRef = ref(null)

    watch(() => props.message, (message) => {
      const thinking =
        message.match(THOUGHT_REGEX_OPEN) && !message.match(THOUGHT_REGEX_CLOSE)

      if (thinking && thoughtChainRef.value) {
        thoughtChainRef.value.updateContent(message)
        return
      }

      const completeThoughtChain = message.match(THOUGHT_REGEX_COMPLETE)?.[0]
      const msgToRender = message.replace(THOUGHT_REGEX_COMPLETE, '')

      if (completeThoughtChain && thoughtChainRef.value) {
        thoughtChainRef.value.updateContent(completeThoughtChain)
      }

      contentRef.value = msgToRender
    }, { immediate: true })

    return () => {
      const thinking =
        props.message.match(THOUGHT_REGEX_OPEN) && !props.message.match(THOUGHT_REGEX_CLOSE)

      if (thinking) {
        return h(ThoughtContainer, { ref: thoughtChainRef, content: '', expanded: true })
      }

      return h('div', { class: 'flex flex-col gap-y-1' }, [
        props.message.match(THOUGHT_REGEX_COMPLETE)
          ? h(ThoughtContainer, { ref: thoughtChainRef, content: '', expanded: true })
          : null,
        h('span', {
          class: 'break-words',
          innerHTML: renderMarkdown(contentRef.value)
        })
      ])
    }
  }
})
</script>

<template>
  <div v-if="!reply && sources.length === 0 && !pending && !error"></div>

  <div
    v-else-if="pending"
    :class="`flex justify-center items-end w-full ${assistantBackgroundColor}`"
  >
    <div class="py-6 px-4 w-full flex gap-x-5 md:max-w-[80%] flex-col">
      <div class="flex gap-x-5">
        <WorkspaceProfileImage :workspace="workspace" />
        <div class="mt-3 ml-5 dot-falling light:invert"></div>
      </div>
    </div>
  </div>

  <div
    v-else-if="error"
    :class="`flex justify-center items-end w-full ${assistantBackgroundColor}`"
  >
    <div class="py-6 px-4 w-full flex gap-x-5 md:max-w-[80%] flex-col">
      <div class="flex gap-x-5">
        <WorkspaceProfileImage :workspace="workspace" />
        <span class="inline-block p-2 rounded-lg bg-red-50 text-red-500">
          <Warning class="h-4 w-4 mb-1 inline-block" /> Could not
          respond to message.
          <span class="text-xs">Reason: {{ error || 'unknown' }}</span>
        </span>
      </div>
    </div>
  </div>

  <div
    v-else
    :key="uuid"
    :class="`flex justify-center items-end w-full ${assistantBackgroundColor}`"
  >
    <div class="py-8 px-4 w-full flex gap-x-5 md:max-w-[80%] flex-col">
      <div class="flex gap-x-5">
        <WorkspaceProfileImage :workspace="workspace" />
        <RenderAssistantChatContent
          :key="`${uuid}-prompt-reply-content`"
          :message="reply"
        />
      </div>
      <Citations :sources="sources" />
    </div>
  </div>
</template>
